services:
  # Ollama - Local LLM Runtime for Development Testing
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - litellm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # PostgreSQL Database - Local Development
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=litellm_db
      - POSTGRES_USER=litellm_user
      - POSTGRES_PASSWORD=litellm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - litellm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm_user -d litellm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LiteLLM Proxy - Local Development
  litellm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litellm-proxy
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      - LITELLM_MASTER_KEY=sk-local-dev-key-12345
      - DATABASE_URL=postgresql://litellm_user:litellm_password@postgres:5432/litellm_db
    networks:
      - litellm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  litellm-network:
    driver: bridge

volumes:
  ollama_data:
  postgres_data:
