model_list:
  - model_name: llama3.2-3b
    litellm_params:
      # Llama 3.2 3B on containerized Ollama
      model: ollama/llama3.2:3b
      api_base: http://ollama:11434
      
  - model_name: deepseek-r1-1.5b
    litellm_params:
      # DeepSeek R1 1.5B on containerized Ollama
      model: ollama/deepseek-r1:1.5b
      api_base: http://ollama:11434

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  litellm_settings:
    json_logs: true
    set_verbose: false
  health_check_details: false

# Modular PII Detection Guardrails - Mix and match as needed
guardrails:
  - guardrail_name: "pii-regex-precall"
    litellm_params:
      guardrail: pii_regex_precall.PIIRegexPreCallGuardrail
      mode: ["pre_call"]
      default_on: false
      
  - guardrail_name: "pii-regex-postcall"
    litellm_params:
      guardrail: pii_regex_postcall.PIIRegexPostCallGuardrail
      mode: ["post_call"]
      default_on: false
      
  - guardrail_name: "pii-presidio"
    litellm_params:
      guardrail: presidio
      mode: ["pre_call","post_call"] 
      default_on: false
      presidio_language: "en"
      pii_entities_config:
        EMAIL_ADDRESS: "BLOCK"
        US_SSN: "BLOCK"
        PHONE_NUMBER: "BLOCK"
        CREDIT_CARD: "BLOCK"
        PERSON: "BLOCK"
        LOCATION: "BLOCK"
